#%RAML 1.0 NamedExample
value:
  name: "My Application Alert"
  description: "Error getting Customers data"
  level: "ERROR"
  date: 2018-07-02T15:00:00Z
  message: "An error ocurred during the transfer of Customer data from the ABC system"
  receipts: ["example.example@mulesoft.com","another.example@mulesoft.com"]
  applicationName: "my-amazing-api"
  environment: "PROD"
  documentationLink: "https://en.wikipedia.org/wiki/Software_developer"
  imageLink: "https://www.mulesoft.com/sites/default/files/mulesoft-logo-open-graph.png"