#%RAML 1.0 Trait
responses: 
  500:
    body: 
      application/json:
        type: object
        properties: 
          message: string
        example:
          value:
            message: Internal Server Error